### ISSUE TITLE
Robot meshes and structure are not correctly shown

### ISSUE THREAD

**Issue by fmrico** [clearpathrobotics/clearpath_simulator#11]
- OS: Ubuntu 22.04
 - ROS 2 Distro: Humble
 - Built from source
 - Package version: 
   - clearpath_common: humble
   - clearpath_config: main
   - clearpath_robot: main
   - clearpath_simulator: main
   - Ignition Gazebo, version 6.14.0

 **Expected behaviour**
I am following the documentation at: https://docs.clearpathrobotics.com/docs/ros/config/yaml . My robot.yaml is:

```
serial_number: a200-0000
version: 0
system:
  hosts:
    self: argo
    platform:
      argo: 127.0.0.1
    onboard: {}
    remote: {}
  ros2:
    username: fmrico
    namespace: /
    domain_id: 0
    rmw_implementation: rmw_fastrtps_cpp
platform:
  controller: ps4
  decorations:
    front_bumper:
      enabled: true
      model: default
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      extension: 0.0
    rear_bumper:
      enabled: true
      model: default
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      extension: 0.0
    structure:
      enabled: true
      model: sensor_arch_300
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
    top_plate:
      enabled: true
      model: pacs
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
  extras:
    urdf: null
    control: null
accessories:
  box:
    - name: user_bay_cover
      parent: top_plate_link
      xyz: [0.0, 0.0, 0.00735]
      rpy: [0.0, 0.0, 0.0]
      size: [0.4, 0.4, 0.002]
  cylinder: []
  link: []
  mesh: []
  sphere: []
mounts:
  bracket: []
  fath_pivot: []
  riser: []
sensors:
  camera: []
  gps: []
  imu: []
  lidar2d: []
  lidar3d: []
```

It is supposed to get this:

![husky_platform_2-8bf19f7212c4da8e9d51d5964354c9c2](https://github.com/clearpathrobotics/clearpath_simulator/assets/3810011/f5a20bb9-0757-45c1-9bd7-8cb973e61bc8)

 **Actual behaviour**
 I get this: 

![Captura desde 2023-08-09 09-39-55](https://github.com/clearpathrobotics/clearpath_simulator/assets/3810011/87cad0c6-dc65-46c7-8d9f-a5a1bea69b4f)

**To Reproduce**
Simply follow your instructions:
1. Clone the above packages in a workspace and build
2. store the robot.yaml file I shown before in `~/clearpath/`
3. ros2 launch clearpath_gz simulation.launch.py
