### ISSUE TITLE
Incorrect TF frame for Stereolabs ZED camera

### ISSUE THREAD

**Issue by AllenIsaacJose** [clearpathrobotics/clearpath_simulator#62]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS 2 Distro: Humble
 - Built from source or installed: installed
 - Package version: [2edd54c](https://github.com/clearpathrobotics/clearpath_simulator/commit/2edd54c07a37262c96839c36b0303794354cbad5)

 **Expected behaviour**
 The camera topics are connected to the base_link when visualized using:
```
ros2 run rqt_tf_tree rqt_tf_tree --ros-args -r /tf:=/NAMESPACE/tf -r /tf_static:=/NAMESPACE/tf_static
```

 **Actual behaviour**
The **/NAMESPACE/robot/base_link/camera_0** frame is connected to **camera_0_link** and this part is disconnected from the main TF tree. The issue is that, the automatically generated **clearpath/husky/sensors/launch/camera_0.launch.py** file contains a node for static transform publisher **node_camera_0_static_tf** which expects the frame id to be **camera_0_link** which is not correct in the case of ZED camera(it will work for realsense camera). For ZED camera, it expects **camera_0_camera_link**. Since i dont want to break the clearpath simulator code, I changed the URDF file for ZED camera within **zed_wrapper** package from **xxx_camera_link** to **xxx_link** as a workaround.

**To Reproduce**
Provide the steps to reproduce:
1. Create a robot.yaml file with the below sensors configuration(for Husky) and visualize using **rqt_tf_tree**. We can see the disconnected camera component from the main TF tree.
```
- model: stereolabs_zed
      urdf_enabled: true
      launch_enabled: true
      parent: fath_pivot_0_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [3.14159, 0.0, 0.0]
      ros_parameters:
        stereolabs_zed:
          general.camera_name: camera_0
          general.camera_model: 'zed2i'
```
