### ISSUE TITLE
Using ouster-os1 in simulation

### ISSUE THREAD

**Issue by aoran-jiao** [clearpathrobotics/clearpath_simulator#95]
**Please provide the following information:**
 - OS: ubuntu 22.04
 - ROS 2 Distro: humble
 - Built from source or installed: installed
 - Package version: humble branch
 - Real hardware or simulation: Simulation

 **Expected behaviour**
 I tried to use ouster_os1 as the lidar3d model, referencing the `ouster_os1.yaml`. I expect the point cloud and lidar images (signal, range, reflectivity, etc.)

 **Actual behaviour**
The urdf spawns and I can see the ouster lidar in gazebo, but I cannot see any lidar ros topics. I checked that the lidar3d_0.yaml file was empty in my `~/clearpath/sensors/config`

**To Reproduce**
The following is my `~/clearpath/robot.yaml`
```
serial_number: w200-0000
version: 0
system:
  username: administrator
  hosts:
    - hostname: cpr-w200-0000
      ip: 192.168.131.1
  ros2:
    namespace: w200_0000
    domain_id: 0
    middleware:
      discovery: server
      servers:
        - hostname: cpr-w200-0000

links:
  box:
    - name: structure
      size: [0.5, 0.675, .5]
    - name: tower
      size: [0.15, 0.15, 0.5]
      parent: structure_link
      xyz: [0.0, 0.0, 0.5]
  frame:
    - name: top_tower
      parent: tower_link
      xyz: [0.0, 0.0, 0.25]
mounts:
  disk:
    - parent: post_0_mount
  post:
    - model: dual
      parent: top_tower_link
      xyz: [0.0, 0.0, 0.5]
      spacing: 0.12
sensors:
  camera:
    - model: intel_realsense
      urdf_enabled: true
      launch_enabled: true
      parent: disk_0_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        intel_realsense:
          camera_name: camera_0
          device_type: d435
          serial_no: '0'
          enable_color: true
          rgb_camera.profile: 640,480,30
          enable_depth: true
          depth_module.profile: 640,480,30
          pointcloud.enable: true

  gps:
    - model: novatel_smart7
      urdf_enabled: true
      launch_enabled: true
      parent: base_link
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        nmea_navsat_driver:
          frame_id: gps_0_link
          port: "/dev/clearpath/gps"
          baud: 115200

  lidar3d:
    - model: ouster_os1
      urdf_enabled: true
      launch_enabled: true
      parent: disk_0_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        ouster_driver:
          sensor_hostname: 192.168.131.20
          udp_dest: 192.168.131.100
          lidar_port: 7502
          imu_port: 7503
          proc_mask: IMU|PCL|SCAN|IMG|RAW|TLM
          use_system_default_qos: false
```

Thank you for your time!
